# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Pester@10
  displayName: Run Pester Tests, Yay!
  inputs:
    scriptFolder: '$(System.DefaultWorkingDirectory)\*'
    resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
    usePSCore: False

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/Test-Pester.XML'
    failTaskOnFailedTests: true